language:
  - python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_script:
  - pip3 install mysql-connector
  - pip3 install mysql-connector-python
script:
  - python3 -m pytest book.py
